import re, os

os.chdir(r'D:\MEox\UITer\DOAN\Mosco_Megre\Mosco\raw-doc')
with open('03_chuong_3_phan_tich_thiet_ke.md', 'r', encoding='utf-8') as f:
    text = f.read()

# ============ COMPREHENSIVE VIETNAMESE FIX ============
# The ? replaces characters outside Windows-1252 range (U+0100+)
# We fix based on Vietnamese word context

replacements = {}

def add(word, correct):
    replacements[word] = correct

# === NAVIGATION / UI ELEMENTS ===
add('B?ng', 'Bảng'); add('b?ng', 'bảng')
add('B?n', 'Bản'); add('b?n', 'bản')
add('B?t', 'Bắt'); add('b?t', 'bắt')
add('B?i', 'Bài'); add('b?i', 'bài')
add('B?o', 'Bảo'); add('b?o', 'bảo')
add('B?m', 'Bấm'); add('b?m', 'bấm')
add('Bu?c', 'Buộc'); add('bu?c', 'buộc')
add('B?o v?', 'Bảo vệ')
add('b?o v?', 'bảo vệ')

# === VERBS / ACTIONS ===
add('Ch?n', 'Chọn'); add('ch?n', 'chọn')
add('Ch?a', 'Chứa'); add('ch?a', 'chứa')
add('Ch?m', 'Chậm'); add('ch?m', 'chậm')
add('Ch?ng', 'Chứng'); add('ch?ng', 'chứng')
add('Ch?nh', 'Chỉnh'); add('ch?nh', 'chỉnh')
add('Ch?p', 'Chấp'); add('ch?p', 'chấp')
add('Ch?t', 'Chất'); add('ch?t', 'chất')
add('Ch?y', 'Chạy'); add('ch?y', 'chạy')
add('C?p', 'Cấp'); add('c?p', 'cấp')
add('C?t', 'Cắt'); add('c?t', 'cắt')
add('C?i', 'Cải'); add('c?i', 'cải')
add('C?m', 'Cảm'); add('c?m', 'cảm')
add('C?u', 'Cầu'); add('c?u', 'cầu')
add('C?ng', 'Cộng'); add('c?ng', 'cộng')
add('C?nh', 'Cảnh'); add('c?nh', 'cảnh')
add('D?ng', 'Dựng'); add('d?ng', 'dựng')
add('D?ch', 'Dịch'); add('d?ch', 'dịch')
add('D?m', 'Đảm'); add('d?m', 'đảm')
add('D?n', 'Đến'); add('d?n', 'đến')
add('D?nh', 'Định'); add('d?nh', 'định')
add('D?p', 'Đẹp'); add('d?p', 'đẹp')
add('D?t', 'Đặt'); add('d?t', 'đặt')
add('D?u', 'Đều'); add('d?u', 'đều')
add('d? l?y', 'để lấy')
add('d? c?p', 'đề cập')
add('D?a', 'Dựa'); add('d?a', 'dựa')
add('D?i', 'Đội'); add('d?i', 'đội')
add('D?y', 'Dạy'); add('d?y', 'dạy')

# === ADJECTIVES / DESCRIPTORS ===
add('C?c', 'Các'); add('c?c', 'các')
add('M?i', 'Mỗi'); add('m?i', 'mỗi')
add('M?t', 'Mặt'); add('m?t', 'mặt')
add('M?m', 'Mềm'); add('m?m', 'mềm')
add('M?u', 'Mẫu'); add('m?u', 'mẫu')
add('M?nh', 'Mạnh'); add('m?nh', 'mạnh')
add('M?i (new)', 'Mới'); 
add('m?i (new)', 'mới')
add('R?t', 'Rất'); add('r?t', 'rất')
add('T?t', 'Tất'); add('t?t', 'tất')
add('Nh?t', 'Nhất'); add('nh?t', 'nhất')
add('Nhi?u', 'Nhiều'); add('nhi?u', 'nhiều')
add('kh?c', 'khác'); add('Kh?c', 'Khác')
add('kh?i', 'khởi'); add('Kh?i', 'Khởi')

# === NOUNS / CONCEPTS ===
add('N?i', 'Nội'); add('n?i', 'nội')
add('N?p', 'Nạp'); add('n?p', 'nạp')
add('N?n', 'Nền'); add('n?n', 'nền')
add('N?u', 'Nếu'); add('n?u', 'nếu')
add('K?', 'Kế'); add('k?', 'kế')
add('K?t', 'Kết'); add('k?t', 'kết')
add('L?p', 'Lớp'); add('l?p', 'lớp')
add('L?n', 'Lần'); add('l?n', 'lần')
add('L?i', 'Lại'); add('l?i', 'lại')
add('L?y', 'Lấy'); add('l?y', 'lấy')
add('L?c', 'Lực'); add('l?c', 'lực')
add('L?ng', 'Lộng'); add('l?ng', 'lộng')
add('L?ch', 'Lịch'); add('l?ch', 'lịch')
add('L?nh', 'Lệnh'); add('l?nh', 'lệnh')
add('L?t', 'Lật'); add('l?t', 'lật')
add('L?i', 'Lợi'); add('l?i', 'lợi')
add('S?', 'Số'); add('s?', 'số')
add('s?n', 'sẵn')
add('S?p', 'Sắp'); add('s?p', 'sắp')
add('S?ch', 'Sạch'); add('s?ch', 'sạch')
add('T?p', 'Tập'); add('t?p', 'tập')
add('T?i', 'Tại'); add('t?i', 'tại')
add('T?c', 'Tức'); add('t?c', 'tức')
add('T?m', 'Tìm'); add('t?m', 'tìm')
add('T?o', 'Tạo'); add('t?o', 'tạo')
add('T?ng', 'Tổng'); add('t?ng', 'tổng')
add('T?n', 'Tận'); add('t?n', 'tận')
add('T?i', 'Tối'); add('t?i', 'tối')
add('t?c d?', 'tốc độ')

# === VERBS (more) ===
add('C?n', 'Cần'); add('c?n', 'cần')
add('C?a', 'Của'); add('c?a', 'của')
add('G?i', 'Gọi'); add('g?i', 'gọi')
add('G?m', 'Gồm'); add('g?m', 'gồm')
add('G?n', 'Gần'); add('g?n', 'gần')
add('G?p', 'Gặp'); add('g?p', 'gặp')
add('G?c', 'Gốc'); add('g?c', 'gốc')
add('H?c', 'Học'); add('h?c', 'học')
add('H?i', 'Hỏi'); add('h?i', 'hỏi')
add('H?n', 'Hơn'); add('h?n', 'hơn')
add('H?o', 'Hảo'); add('h?o', 'hảo')
add('H?t', 'Hết'); add('h?t', 'hết')
add('H?u', 'Hậu'); add('h?u', 'hậu')
add('H?ng', 'Hạng'); add('h?ng', 'hạng')
add('H?p', 'Hợp'); add('h?p', 'hợp')
add('H?y', 'Hủy'); add('h?y', 'hủy')

# === COMMON VIETNAMESE WORDS ===
add('Ph?i', 'Phải'); add('ph?i', 'phải')
add('Ph?n', 'Phần'); add('ph?n', 'phần')
add('Ph?i (role)', 'Phối'); add('ph?i (role)', 'phối')
add('Ph?m', 'Phạm'); add('ph?m', 'phạm')
add('Ph?c', 'Phức'); add('ph?c', 'phức')
add('Ph?ng', 'Phòng'); add('ph?ng', 'phòng')
add('Ph?y', 'Phẩy'); add('ph?y', 'phẩy')
add('V?n', 'Vấn'); add('v?n', 'vấn')
add('V?i', 'Với'); add('v?i', 'với')
add('V?t', 'Vật'); add('v?t', 'vật')
add('Vi?c', 'Việc'); add('vi?c', 'việc')
add('Vi?t', 'Viết'); add('vi?t', 'viết')
add('Vi?n', 'Viên'); add('vi?n', 'viên')
add('X?y', 'Xảy'); add('x?y', 'xảy')
add('X?p', 'Xếp'); add('x?p', 'xếp')
add('Xu?t', 'Xuất'); add('xu?t', 'xuất')
add('Xu?ng', 'Xuống'); add('xu?ng', 'xuống')
add('Y?u', 'Yếu'); add('y?u', 'yếu')

# === MODIFIERS ===
add('Th?i', 'Thời'); add('th?i', 'thời')
add('Th?c', 'Thực'); add('th?c', 'thực')
add('Th?m', 'Thẩm'); add('th?m', 'thẩm')
add('Th?p', 'Thấp'); add('th?p', 'thấp')
add('Th?t', 'Thật'); add('th?t', 'thật')
add('Th?y', 'Thấy'); add('th?y', 'thấy')
add('Th?a', 'Thừa'); add('th?a', 'thừa')
add('Th?ng', 'Thẳng'); add('th?ng', 'thẳng')
add('Thi?n', 'Thiện'); add('thi?n', 'thiện')
add('Thi?u', 'Thiếu'); add('thi?u', 'thiếu')
add('Thi?t', 'Thiết'); add('thi?t', 'thiết')
add('Thuy?t', 'Thuyết'); add('thuy?t', 'thuyết')
add('Ti?p', 'Tiếp'); add('ti?p', 'tiếp')
add('Ti?n', 'Tiến'); add('ti?n', 'tiến')
add('Ti?t', 'Tiết'); add('ti?t', 'tiết')
add('Tri?n', 'Triển'); add('tri?n', 'triển')
add('Tri?t', 'Triệt'); add('tri?t', 'triệt')
add('Tr?c', 'Trực'); add('tr?c', 'trực')
add('Tr?ng', 'Trọng'); add('tr?ng', 'trọng')
add('Tr?i', 'Trời'); add('tr?i', 'trời')
add('Tr?n', 'Trần'); add('tr?n', 'trần')
add('Tru?c', 'Trước'); add('tru?c', 'trước')
add('Tru?ng', 'Trường'); add('tru?ng', 'trường')
add('Tru?t', 'Trượt'); add('tru?t', 'trượt')
add('Truy?n', 'Truyền'); add('truy?n', 'truyền')
add('Tu?n', 'Tuần'); add('tu?n', 'tuần')
add('Tu?ng', 'Tường'); add('tu?ng', 'tường')
add('Tuy?n', 'Tuyến'); add('tuy?n', 'tuyến')
add('Tuy?t', 'Tuyệt'); add('tuy?t', 'tuyệt')
add('Chuy?n', 'Chuyển'); add('chuy?n', 'chuyển')
add('Chi?u', 'Chiều'); add('chi?u', 'chiều')
add('Chu?i', 'Chuỗi'); add('chu?i', 'chuỗi')
add('Chu?n', 'Chuẩn'); add('chu?n', 'chuẩn')
add('Cu?n', 'Cuộn'); add('cu?n', 'cuộn')

# === V, Đ ETC ===
add('Đ?C', 'ĐỨC'); add('Đ?c', 'Đức'); add('đ?c', 'đức')
add('Đ?i', 'Đội'); add('đ?i', 'đội')
add('Đ?m', 'Đếm'); add('đ?m', 'đếm')
add('Đ?ng', 'Đồng'); add('đ?ng', 'đồng')
add('Đ?nh', 'Đỉnh'); add('đ?nh', 'đỉnh')
add('Đ?p', 'Đẹp'); add('đ?p', 'đẹp')
add('Đ?t', 'Đất'); add('đ?t', 'đất')
add('Đ?u', 'Đấu'); add('đ?u', 'đấu')
add('Đi?m', 'Điểm'); add('đi?m', 'điểm')
add('Đi?u', 'Điều'); add('đi?u', 'điều')
add('Gi?i', 'Giải'); add('gi?i', 'giải')
add('Gi?m', 'Giảm'); add('gi?m', 'giảm')
add('Gi?i (world)', 'Giới'); add('gi?i (world)', 'giới')
add('Gi?a', 'Giữa'); add('gi?a', 'giữa')
add('Gi?ng', 'Giống'); add('gi?ng', 'giống')
add('Gi?t', 'Giật'); add('gi?t', 'giật')
add('Hi?u', 'Hiệu'); add('hi?u', 'hiệu')
add('Hi?n', 'Hiện'); add('hi?n', 'hiện')
add('Hi?m', 'Hiếm'); add('hi?m', 'hiếm')
add('Ki?u', 'Kiểu'); add('ki?u', 'kiểu')
add('Ki?n', 'Kiến'); add('ki?n', 'kiến')
add('Ki?m', 'Kiểm'); add('ki?m', 'kiểm')
add('K?ch', 'Kịch'); add('k?ch', 'kịch')
add('Khi?n', 'Khiến'); add('khi?n', 'khiến')
add('Kh?u', 'Khẩu'); add('kh?u', 'khẩu')
add('Kho?ng', 'Khoảng'); add('kho?ng', 'khoảng')
add('Kho?n', 'Khoản'); add('kho?n', 'khoản')

# === SYSTEM / TECHNICAL ===
add('Ch?c', 'Chức'); add('ch?c', 'chức')
add('Ch?ng tr', 'Chống tr')
add('Ch?c n', 'Chức n')
add('ch?c n', 'chức n')
add('H? th?ng', 'Hệ thống'); add('h? th?ng', 'hệ thống')
add('H? so', 'Hồ sơ'); add('h? so', 'hồ sơ')
add('H? s?', 'Hệ số'); add('h? s?', 'hệ số')
add('THI?T', 'THIẾT'); add('Thi?t', 'Thiết'); add('thi?t', 'thiết')
add('TH?NG', 'THỐNG'); add('th?ng', 'thống')
add('THU?T', 'THUẬT'); add('Thu?t', 'Thuật'); add('thu?t', 'thuật')
add('THU?C', 'THUỘC'); add('Thu?c', 'Thuộc'); add('thu?c', 'thuộc')
add('CH?C', 'CHỨC'); add('Ch?c', 'Chức'); add('ch?c', 'chức')
add('BI?T', 'BIẾT'); add('Bi?t', 'Biết'); add('bi?t', 'biết')
add('GI?I', 'GIẢI'); add('Gi?i', 'Giải'); add('gi?i', 'giải')
add('LI?U', 'LIỆU'); add('Li?u', 'Liệu'); add('li?u', 'liệu')
add('T?N', 'TỒN'); add('t?n', 'tồn')
add('V?N', 'VẤN'); add('v?n', 'vấn')
add('C?T', 'CẮT'); add('c?t', 'cắt')
add('NG?I', 'NGƯỜI'); add('ngu?i', 'người'); add('Ngu?i', 'Người')
add('NGHI?P', 'NGHIỆP'); add('nghi?p', 'nghiệp'); add('Nghi?p', 'Nghiệp')
add('PH?I', 'PHỐI')
add('TI?T', 'TIẾT'); add('ti?t', 'tiết')
add('T?I', 'TỐI'); add('t?i', 'tối')

# === DATA / ATTRIBUTE WORDS ===
add('d? li?u', 'dữ liệu'); add('D? li?u', 'Dữ liệu')
add('d? li?u', 'dữ liệu')
add('c?u tr', 'cấu tr')
add('l?u tr?', 'lưu trữ')
add('Lu?ng', 'Luồng'); add('lu?ng', 'luồng')
add('Lu?i', 'Lưới'); add('lu?i', 'lưới')
add('Lu?n', 'Luôn'); add('lu?n', 'luôn')
add('Lu?t', 'Luật'); add('lu?t', 'luật')
add('Lu?c', 'Lược'); add('lu?c', 'lược')
add('Lo?i', 'Loại'); add('lo?i', 'loại')

# === WORDS WITH CONTEXT (phrase patterns) ===
add('Ngu?i d', 'Người d')
add('ngu?i d', 'người d')
add('qu?n l', 'quản l')
add('Qu?n l', 'Quản l')
add('x? l', 'xử l')
add('X? l', 'Xử l')
add('ph?c v?', 'phục vụ')
add('ph?c v?', 'phục vụ')
add('k?t n?i', 'kết nối')
add('d? c?p', 'được cập')
add('d?c t?', 'đặc tả')

# === FIX THE Đ? VARIANT (corrupted Unicode) ===
# These appear as corrupted characters that we need to handle
add('�?C', 'ĐỨC')
add('�?c', 'đức')
add('�?i', 'đội')
add('�?m', 'đếm')
add('�?ng', 'đồng')
add('�?nh', 'đỉnh')
add('�?p', 'đẹp')
add('�?t', 'đất')
add('�?u', 'đấu')
add('?i?m', 'iểm')
add('?i?u', 'iều')

# === TECHNICAL ENGLISH TERMS ===
add('collection?artist', 'collection_artist')
add('etl?key', 'etl_key')
add('sync?lastSyncTime', 'sync_lastSyncTime')
add('batch?pages', 'batch_pages')
add('fetch?page', 'fetch_page')

# === ADDITIONAL COMMON PATTERNS ===
add('So d?', 'Sơ đồ'); add('so d?', 'sơ đồ')
add('Kho d?', 'Kho đồ'); add('kho d?', 'kho đồ')
add('B? su', 'Bộ sư'); add('b? su', 'bộ sư')
add('suu t?', 'sưu t')
add('Mô t?', 'Mô tả'); add('mô t?', 'mô tả')
add('Th? b?i', 'Thẻ bài'); add('th? b?i', 'thẻ bài')
add('th? b?i', 'thẻ bài')
add('Nguy?n l', 'Nguyên l')
add('nguy?n l', 'nguyên l')
add('Th? t?', 'Thứ tự')
add('d?ng b?', 'đồng bộ')
add('Đ?ng b?', 'Đồng bộ')
add('đ?ng b?', 'đồng bộ')
add('B? ph?n', 'Bộ phận')
add('C? th?', 'Cụ thể')
add('c? th?', 'cụ thể')
add('Th? t?', 'Thể hiện')
add('s? li?u', 'số liệu')
add('S? li?u', 'Số liệu')
add('B? nh?', 'Bộ nhớ')
add('b? nh?', 'bộ nhớ')
add('da n?n', 'đa nền')
add('cao nh?t', 'cao nhất')

# Apply all replacements (longest first to match phrases before single words)
sorted_reps = sorted(replacements.items(), key=lambda x: -len(x[0]))
for old, new in sorted_reps:
    text = text.replace(old, new)

# Final count
remaining = len(re.findall(r'\?', text))
print(f'Applied {len(replacements)} replacements')
print(f'Remaining ?: {remaining}')

# Show remaining context if any
if remaining > 0:
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if '?' in line:
            # Find context around ?
            idx = line.find('?')
            start = max(0, idx-10)
            end = min(len(line), idx+10)
            context = line[start:end]
            print(f'  Line {i+1}: ...{context.strip()}...')

with open('03_chuong_3_phan_tich_thiet_ke.md', 'w', encoding='utf-8') as f:
    f.write(text)
