import re, os

os.chdir(r'D:\MEox\UITer\DOAN\Mosco_Megre\Mosco\raw-doc')

with open('03_chuong_3_phan_tich_thiet_ke.md', 'r', encoding='utf-8') as f:
    text = f.read()

# Build comprehensive replacement map for corrupted words
replacements = {
    # Common Vietnamese words with ? corruption
    'THI?T': 'THIẾT', 'thi?t': 'thiết',
    'K?': 'KẾ', 'k?': 'kế',
    'TH?NG': 'THỐNG', 'th?ng': 'thống',
    'H? TH?NG': 'HỆ THỐNG', 'h? th?ng': 'hệ thống',
    'CH?C': 'CHỨC', 'ch?c': 'chức',
    'BI?T': 'BIẾT', 'bi?t': 'biết',
    'THU?T': 'THUẬT', 'thu?t': 'thuật',
    'THU?C': 'THUỘC', 'thu?c': 'thuộc',
    'Ngu?i': 'Người', 'ngu?i': 'người',
    'Nghi?p': 'Nghiệp', 'nghi?p': 'nghiệp',
    'D?a': 'Dựa', 'd?a': 'dựa',
    'Ph?n': 'Phần', 'ph?n': 'phần',
    'GI?I': 'GIẢI', 'Gi?i': 'Giải', 'gi?i': 'giải',
    'LI?U': 'LIỆU', 'Li?u': 'Liệu', 'li?u': 'liệu',
    'C?c': 'Các', 'c?c': 'các',
    'C?p': 'Cấp', 'c?p': 'cấp',
    'T?p': 'Tập', 't?p': 'tập',
    'Ph?i': 'Phải', 'ph?i': 'phải',
    'Hi?u': 'Hiệu', 'hi?u': 'hiệu', 'hi?n': 'hiện', 'Hi?n': 'Hiện',
    'Ki?u': 'Kiểu', 'ki?u': 'kiểu',
    'M?i': 'Mỗi', 'm?i': 'mỗi',
    'T?i': 'Tại', 't?i': 'tại',
    'L?y': 'Lấy', 'l?y': 'lấy',
    'Ch?n': 'Chọn', 'ch?n': 'chọn',
    'T?N': 'TỒN', 'T?c': 'Tức', 't?c': 'tức',
    'N?u': 'Nếu', 'n?u': 'nếu',
    'V?N': 'VẤN', 'V?n': 'Vấn', 'v?n': 'vấn',
    'C?T': 'CẮT', 'c?t': 'cắt',
    'N?i': 'Nội', 'n?i': 'nội', 'N?p': 'Nạp', 'n?p': 'nạp',
    'T?t': 'Tất', 't?t': 'tất',
    'Nh?t': 'Nhất', 'nh?t': 'nhất',
    'L?n': 'Lần', 'l?n': 'lần',
    'L?i': 'Lại', 'l?i': 'lại',
    'T?ng': 'Tổng', 't?ng': 'tổng',
    'B?ng': 'Bảng', 'b?ng': 'bảng',
    'S?': 'Số', 's?': 'số', 's?n': 'sẵn',
    'M?t': 'Mặt', 'm?t': 'mặt',
    'M?': 'Mỹ', 'm?c': 'mức', 'M?c': 'Mức',
    'B?i': 'Bài', 'b?i': 'bài',
    'B?n': 'Bạn', 'b?n': 'bạn',
    'R?t': 'Rất', 'r?t': 'rất',
    'L?p': 'Lớp', 'l?p': 'lớp',
    'K?t': 'Kết', 'k?t': 'kết',
    'H?ng': 'Hạng', 'h?ng': 'hạng',
    'H?p': 'Hợp', 'h?p': 'hợp',
    'H?y': 'Hủy', 'h?y': 'hủy',
    'Gi?m': 'Giảm', 'gi?m': 'giảm',
    'Gi?i': 'Giới', 'gi?i': 'giới',
    'L?ch': 'Lịch', 'l?ch': 'lịch',
    'L?ng': 'Lộng', 'l?ng': 'lộng',
    'M?i': 'Mới', 'm?i': 'mới',
    'M?m': 'Mềm', 'm?m': 'mềm',
    'M?ng': 'Mừng', 'm?ng': 'mừng',
    'N?i': 'Nơi', 'n?i': 'nơi',
    'B?t': 'Bắt', 'b?t': 'bắt',
    'B?o': 'Bảo', 'b?o': 'bảo',
    'B?m': 'Bấm', 'b?m': 'bấm',
    'C?a': 'Của', 'c?a': 'của',
    'C?n': 'Cần', 'c?n': 'cần',
    'C?ng': 'Cộng', 'c?ng': 'cộng',
    'C?nh': 'Cảnh', 'c?nh': 'cảnh',
    'C?i': 'Cải', 'c?i': 'cải',
    'C?m': 'Cảm', 'c?m': 'cảm',
    'C?u': 'Cầu', 'c?u': 'cầu',
    'Ch?a': 'Chứa', 'ch?a': 'chứa',
    'Ch?m': 'Chậm', 'ch?m': 'chậm',
    'Ch?ng': 'Chứng', 'ch?ng': 'chứng',
    'Ch?nh': 'Chỉnh', 'ch?nh': 'chỉnh',
    'Ch?p': 'Chấp', 'ch?p': 'chấp',
    'Ch?t': 'Chất', 'ch?t': 'chất',
    'Ch?y': 'Chạy', 'ch?y': 'chạy',
    'D?c': 'Đặc', 'd?c': 'đặc',
    'D?ch': 'Dịch', 'd?ch': 'dịch',
    'D?i': 'Đại', 'd?i': 'đại',
    'D?m': 'Đảm', 'd?m': 'đảm',
    'D?n': 'Đến', 'd?n': 'đến',
    'D?ng': 'Động', 'd?ng': 'động',
    'D?nh': 'Định', 'd?nh': 'định',
    'D?p': 'Đẹp', 'd?p': 'đẹp',
    'D?t': 'Đặt', 'd?t': 'đặt',
    'D?u': 'Đều', 'd?u': 'đều',
    'D?y': 'Dạy', 'd?y': 'dạy',
    'G?c': 'Gốc', 'g?c': 'gốc',
    'G?i': 'Gọi', 'g?i': 'gọi',
    'G?m': 'Gồm', 'g?m': 'gồm',
    'G?n': 'Gần', 'g?n': 'gần',
    'G?p': 'Gặp', 'g?p': 'gặp',
    'H?c': 'Học', 'h?c': 'học',
    'H?i': 'Hỏi', 'h?i': 'hỏi',
    'H?n': 'Hơn', 'h?n': 'hơn',
    'H?o': 'Hảo', 'h?o': 'hảo',
    'H?t': 'Hết', 'h?t': 'hết',
    'H?u': 'Hậu', 'h?u': 'hậu',
    'K?ch': 'Kịch', 'k?ch': 'kịch',
    'Kh?c': 'Khác', 'kh?c': 'khác',
    'Kh?i': 'Khởi', 'kh?i': 'khởi',
    'Kh?u': 'Khẩu', 'kh?u': 'khẩu',
    'L?c': 'Lực', 'l?c': 'lực',
    'L?nh': 'Lệnh', 'l?nh': 'lệnh',
    'M?u': 'Mẫu', 'm?u': 'mẫu',
    'Ng?u': 'Ngẫu', 'ng?u': 'ngẫu',
    'Ngh?n': 'Nghìn', 'ngh?n': 'nghìn',
    'Nhi?u': 'Nhiều', 'nhi?u': 'nhiều',
    'Nh?m': 'Nhằm', 'nh?m': 'nhằm',
    'Nh?n': 'Nhận', 'nh?n': 'nhận',
    'Nh?ng': 'Những', 'nh?ng': 'những',
    'Nh?p': 'Nhập', 'nh?p': 'nhập',
    'Ph?m': 'Phạm', 'ph?m': 'phạm',
    'Quy?n': 'Quyền', 'quy?n': 'quyền',
    'Th?a': 'Thừa', 'th?a': 'thừa',
    'Th?i': 'Thời', 'th?i': 'thời',
    'Th?m': 'Thẩm', 'th?m': 'thẩm',
    'Th?p': 'Thấp', 'th?p': 'thấp',
    'Th?t': 'Thật', 'th?t': 'thật',
    'Th?y': 'Thấy', 'th?y': 'thấy',
    'Ti?p': 'Tiếp', 'ti?p': 'tiếp',
    'Tr?c': 'Trực', 'tr?c': 'trực',
    'Tr?ng': 'Trọng', 'tr?ng': 'trọng',
    'Tri?n': 'Triển', 'tri?n': 'triển',
    'Tri?t': 'Triệt', 'tri?t': 'triệt',
    'Tuy?n': 'Tuyến', 'tuy?n': 'tuyến',
    'Tuy?t': 'Tuyệt', 'tuy?t': 'tuyệt',
    'Vi?c': 'Việc', 'vi?c': 'việc',
    'Vi?t': 'Viết', 'vi?t': 'viết',
    'Xu?t': 'Xuất', 'xu?t': 'xuất',
    'Y?u': 'Yếu', 'y?u': 'yếu',
    'Đ?C': 'ĐỨC', 'Đ?c': 'Đức', 'đ?c': 'đức',
    'Đ?i': 'Đội', 'đ?i': 'đội',
    'Đ?m': 'Đếm', 'đ?m': 'đếm',
    'Đ?ng': 'Đồng', 'đ?ng': 'đồng',
    'Đ?nh': 'Đỉnh', 'đ?nh': 'đỉnh',
    'Đ?p': 'Đẹp', 'đ?p': 'đẹp',
    'Đ?t': 'Đất', 'đ?t': 'đất',
    'Đ?u': 'Đấu', 'đ?u': 'đấu',
    'Đi?m': 'Điểm', 'đi?m': 'điểm',
    'Đi?u': 'Điều', 'đi?u': 'điều',
    'B?i c?nh': 'Bối cảnh', 'b?i c?nh': 'bối cảnh',
    'Nghi?m': 'Nghiêm',
    'Ph?ng': 'Phòng', 'ph?ng': 'phòng',
    'Ph?c': 'Phức', 'ph?c': 'phức',
    'Ph?y': 'Phẩy', 'ph?y': 'phẩy',
    'Lu?ng': 'Lượng', 'lu?ng': 'lượng',
    'Lu?i': 'Lưới', 'lu?i': 'lưới',
    'Lu?n': 'Luôn', 'lu?n': 'luôn',
    'L?t': 'Lật', 'l?t': 'lật',
    'L?': 'Lệ',
    'Lo?i': 'Loại', 'lo?i': 'loại',
    'Ki?n': 'Kiến', 'ki?n': 'kiến',
    'Ki?m': 'Kiểm', 'ki?m': 'kiểm',
    'Kho?ng': 'Khoảng', 'kho?ng': 'khoảng',
    'Kho?n': 'Khoản', 'kho?n': 'khoản',
    'Khi?n': 'Khiến', 'khi?n': 'khiến',
    'Gi?a': 'Giữa', 'gi?a': 'giữa',
    'Gi?ng': 'Giống', 'gi?ng': 'giống',
    'Gi?t': 'Giật', 'gi?t': 'giật',
    'Di?n': 'Diễn', 'di?n': 'diễn',
    'Di?m': 'Diệm', 'di?m': 'diểm',
    'Di?u': 'Diệu', 'di?u': 'diệu',
    'Do?n': 'Đoạn', 'do?n': 'đoạn',
    'Du?c': 'Được', 'du?c': 'được',
    'Du?i': 'Dưới', 'du?i': 'dưới',
    'Du?ng': 'Đường', 'du?ng': 'đường',
    'Duy?t': 'Duyệt', 'duy?t': 'duyệt',
    'Chu?i': 'Chuỗi', 'chu?i': 'chuỗi',
    'Chu?n': 'Chuẩn', 'chu?n': 'chuẩn',
    'Chuy?n': 'Chuyển', 'chuy?n': 'chuyển',
    'Chi?u': 'Chiều', 'chi?u': 'chiều',
    'Cu?n': 'Cuộn', 'cu?n': 'cuộn',
    'Ho?c': 'Hoặc', 'ho?c': 'hoặc',
    'Ho?t': 'Hoạt', 'ho?t': 'hoạt',
    'Hu?ng': 'Hướng', 'hu?ng': 'hướng',
    'Ng?a': 'Ngửa', 'ng?a': 'ngửa',
    'Ng?m': 'Ngầm', 'ng?m': 'ngầm',
    'Ng?t': 'Ngắt', 'ng?t': 'ngắt',
    'Ngh?n': 'Nghẹn',
    'Ngo?i': 'Ngoại', 'ngo?i': 'ngoại',
    'Ngu?n': 'Nguồn', 'ngu?n': 'nguồn',
    'Ngu?ng': 'Ngưỡng', 'ngu?ng': 'ngưỡng',
    'Ni?m': 'Niềm', 'ni?m': 'niềm',
    'Qu?n': 'Quản', 'qu?n': 'quản',
    'Quy?t': 'Quyết', 'quy?t': 'quyết',
    'R?i': 'Rồi', 'r?i': 'rồi',
    'Ru?m': 'Ruộm',
    'S?a': 'Sửa', 's?a': 'sửa', 's?c': 'sức',
    'S?ch': 'Sạch', 's?ch': 'sạch',
    'S?p': 'Sắp', 's?p': 'sắp',
    'Su?t': 'Suốt', 'su?t': 'suốt',
    'T?a': 'Tọa', 't?a': 'tọa',
    'T?m': 'Tìm', 't?m': 'tìm',
    'T?o': 'Tạo', 't?o': 'tạo',
    'Th?c': 'Thực', 'th?c': 'thực',
    'Th?ng': 'Thẳng', 'th?ng': 'thẳng',
    'Thi?n': 'Thiện', 'thi?n': 'thiện',
    'Thi?u': 'Thiếu', 'thi?u': 'thiếu',
    'Thu?ng': 'Thưởng', 'thu?ng': 'thưởng',
    'Thuy?t': 'Thuyết', 'thuy?t': 'thuyết',
    'Ti?n': 'Tiến', 'ti?n': 'tiến',
    'Ti?t': 'Tiết', 'ti?t': 'tiết',
    'Tr?i': 'Trời', 'tr?i': 'trời',
    'Tr?n': 'Trần', 'tr?n': 'trần',
    'Tru?c': 'Trước', 'tru?c': 'trước',
    'Tru?ng': 'Trường', 'tru?ng': 'trường',
    'Tru?t': 'Trượt', 'tru?t': 'trượt',
    'Tu?n': 'Tuần', 'tu?n': 'tuần',
    'Tu?ng': 'Tường', 'tu?ng': 'tường',
    'V?i': 'Với', 'v?i': 'với',
    'V?t': 'Vật', 'v?t': 'vật',
    'Vi?n': 'Viên', 'vi?n': 'viên',
    'Vu?t': 'Vượt', 'vu?t': 'vượt',
    'X?p': 'Xếp', 'x?p': 'xếp',
    'X?y': 'Xảy', 'x?y': 'xảy',
    'Xu?ng': 'Xuống', 'xu?ng': 'xuống',
    # Additional specific words
    'CH?A': 'CHỮA', 'Ch?a': 'Chữa',
    'TH?I': 'THỂ', 'Th?i': 'Thể', 'th?i': 'thể',
    'X? L': 'Xử L',
    'x? l': 'xử l',
    'N?N': 'NỀN',
    'Truy?n': 'Truyền',
    'truy?n': 'truyền',
    'H?ng': 'Hứng',
    'H? th?ng': 'Hệ thống',
    '?i?m': 'iểm',
    '?i?u': 'iều',
    '?a?u': 'a đầu',
    'b?o': 'bảo',
    'l?c': 'lực',
    # Lines that need special attention
    'c?a h?': 'của hệ',
    'C?a h?': 'Của hệ',
    'T?P': 'TẬP',
    'T?p trung': 'Tập trung',
    't?p trung': 'tập trung',
    'PH?I': 'PHỐI',
    # Batch 2 - remaining words
    'Bi?n': 'Biến', 'bi?n': 'biến',
    'Bu?c': 'Buộc', 'bu?c': 'buộc',
    'T?I': 'TỐI', 't?i': 'tối',
    'TI?T': 'TIẾT', 'ti?t': 'tiết',
    'Thi?t': 'Thiết', 'thi?t': 'thiết',
    'Thu?c': 'Thuộc', 'thu?c': 'thuộc',
    'Thu?t': 'Thuật', 'thu?t': 'thuật',
    'b?c': 'bậc',
    'b?ch': 'bạch',
    'bi?u': 'biểu',
    'hi?m': 'hiếm',
    'lu?c': 'lược',
    'lu?t': 'luật',
    'm?nh': 'mạnh',
    'mu?t': 'mướt',
    'n?n': 'nền',
    'nghi?m': 'nghiêm',
    't?n': 'tận',
    'T?n': 'Tận',
    '?i?m': 'iểm',
    '?i?u': 'iều',
    # The Đ? variants
    '�?C': 'ĐỨC',
    '�?c': 'đức',
    '�?i': 'đội',
    '�?m': 'đếm',
    '�?ng': 'đồng',
    '�?nh': 'đỉnh',
    '�?p': 'đẹp',
    '�?t': 'đất',
    '�?u': 'đấu',
    # The special Unicode corruption
    'ru?m': 'ruộm',
    # English terms with ?
    'collection?artist': 'collection_artist',
    'etl?key': 'etl_key',
    'sync?lastSyncTime': 'sync_lastSyncTime',
    # batch/pages pattern
    'batch?pages': 'batch_pages',
    'fetch?page': 'fetch_page',
}

# Apply replacements (sort by length descending to match longer strings first)
sorted_reps = sorted(replacements.items(), key=lambda x: -len(x[0]))
for old, new in sorted_reps:
    text = text.replace(old, new)

with open('03_chuong_3_phan_tich_thiet_ke.md', 'w', encoding='utf-8') as f:
    f.write(text)

remaining = len(re.findall(r'\?', text))
print(f'Applied {len(replacements)} replacements')
print(f'Remaining ? characters: {remaining}')
