plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.google.services)
}

android {
    namespace 'com.vn.jet.mosco'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId "com.vn.jet.mosco"
        minSdk 28
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    // --- Các thư viện cơ bản ---
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.2.0'
    implementation 'io.github.scwang90:refresh-layout-kernel:2.1.0'

    // --- Firebase (Dùng cho Auth và lưu trữ kho đồ Online) ---
    implementation platform('com.google.firebase:firebase-bom:34.12.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.android.gms:play-services-auth:20.6.0'

    // --- Room Database (Lưu 9000 thẻ Offline cho mượt) ---
    def room_version = "2.5.2"
    implementation "androidx.room:room-runtime:$room_version"
    // Quan trọng: Dùng annotationProcessor thay cho kapt vì mình dùng Java
    annotationProcessor "androidx.room:room-compiler:$room_version"

    // --- Retrofit & Gson (Tải dữ liệu từ GitHub Gist) ---
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    // --- Glide (Hiển thị ảnh thẻ bài từ link imagedelivery) ---
    implementation 'com.github.bumptech.glide:glide:4.15.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.15.1'

    // --- Lottie & Shimmer (Hiệu ứng UI mượt mà) ---
    implementation 'com.facebook.shimmer:shimmer:0.5.0'
    implementation 'com.airbnb.android:lottie:6.1.0'
    implementation 'androidx.browser:browser:1.5.0'

    // --- Image Cropper (UCrop) để căn chỉnh avatar ---
    implementation 'com.github.yalantis:ucrop:2.2.8'

    // --- Google ML Kit Face Detection cho ảnh đại diện Auto-Crop ---
    implementation 'com.google.mlkit:face-detection:16.1.6'
}